# Configuration for actions/labeler
# https://github.com/actions/labeler

# Documentation changes
'type: documentation':
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - '**/*.md'
          - 'README.md'
          - 'CONTRIBUTING.md'
          - 'SECURITY.md'

# CLI package changes
'pkg: cli':
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/cli/**/*'

# Core package changes
'pkg: core':
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/core/**/*'

# VS Code extension changes
'pkg: vscode':
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/vscode-ide-companion/**/*'

# A2A Server changes
'pkg: a2a-server':
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/a2a-server/**/*'

# Test utilities changes
'pkg: test-utils':
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/test-utils/**/*'

# GitHub Actions / CI/CD changes
'area: ci-cd':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**/*'
          - '.github/actions/**/*'

# Dependencies changes
'area: dependencies':
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - '**/package.json'
          - '**/package-lock.json'

# Configuration changes
'area: config':
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.js'
          - '*.config.ts'
          - 'tsconfig.json'
          - 'eslint.config.js'
          - '.prettierrc.json'
          - '.editorconfig'
          - '.nvmrc'

# Build/tooling changes
'area: build':
  - changed-files:
      - any-glob-to-any-file:
          - 'esbuild.config.js'
          - 'scripts/**/*'
          - 'Dockerfile'

# Test changes
'area: tests':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.spec.ts'
          - 'integration-tests/**/*'
          - 'evals/**/*'

# Security-related changes
'area: security':
  - changed-files:
      - any-glob-to-any-file:
          - 'SECURITY.md'
          - '.github/dependabot.yml'

# Breaking changes (need to be manually labeled)
# 'breaking-change': []

# Needs review from maintainers
'needs: review':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/CODEOWNERS'
          - '.github/dependabot.yml'
          - 'LICENSE'
          - 'GEMINI.md'
