name: 'Run tests (with GEMINI API key)'
description: 'Run the project tests; accepts gemini_api_key as input or reads from environment / secrets.'

inputs:
  gemini_api_key:
    description: 'Gemini API key (optional, otherwise read from GEMINI_API_KEY env)'
    required: false
    default: ''

  working-directory:
    description: 'Working directory'
    required: false
    default: './'

runs:
  using: 'composite'
  steps:
    - name: 'Set GEMINI_API_KEY from input if provided'
      shell: 'bash'
      run: |
        if [[ -n "${{ inputs.gemini_api_key }}" ]]; then
          echo "GEMINI_API_KEY=${{ inputs.gemini_api_key }}" >> $GITHUB_ENV
        fi

    - name: 'Fail early if GEMINI_API_KEY missing'
      shell: 'bash'
      run: |
        if [[ -z "${GEMINI_API_KEY}" ]]; then
          echo "::error::GEMINI_API_KEY is not set. Please add it as a repository secret and/or pass it as an input."
          exit 1
        fi
        echo "GEMINI_API_KEY is set (length: ${#GEMINI_API_KEY})."

    - name: 'Run tests (example)'
      shell: 'bash'
      working-directory: '${{ inputs.working-directory }}'
      run: |
        npm ci
        npm run build
        npm run test:ci
