name: 'Run tests (with GEMINI API key)'
description: 'Run the project tests; accepts gemini_api_key as input or reads from environment / secrets.'

inputs:
  gemini_api_key:
    description: 'Gemini API key (optional, otherwise read from GEMINI_API_KEY env)'
    required: false
    default: ''

  working-directory:
    description: 'Working directory'
    required: false
    default: './'

runs:
  using: 'composite'
  steps:
    - name: 'Set GEMINI_API_KEY from input if provided'
      shell: 'bash'
      run: |
        if [[ -n "${{ inputs.gemini_api_key }}" ]]; then
          echo "GEMINI_API_KEY=${{ inputs.gemini_api_key }}" >> $GITHUB_ENV
        fi

    - name: 'Fail early if GEMINI_API_KEY missing'
      shell: 'bash'
      run: |
        if [[ -z "${GEMINI_API_KEY}" ]]; then
          echo "::error::GEMINI_API_KEY is not set. Please add it as a repository secret and/or pass it as an input."
          exit 1
        fi
        echo "GEMINI_API_KEY is set (length: ${#GEMINI_API_KEY})."

    - name: 'Show inputs (debug)'
      shell: 'bash'
      run: |
        echo "working-directory=${{ inputs.working-directory }}"
        # 注意不要在 logs 中輸出實際 API KEY（敏感），只顯示長度或 mask
        echo "GEMINI_API_KEY length: ${#GEMINI_API_KEY}"
        # 實際執行測試命令（示意）
        (cd "${{ inputs.working-directory }}" || exit 1)
        # 在這裡放你的測試啟動指令，例如：
        # npm ci && npm run test:ci
